/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StreamReceiver */

#ifndef _Included_StreamReceiver
#define _Included_StreamReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StreamReceiver
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_hevcdeocderlibrary_StreamReceiver_init
  (JNIEnv *, jclass);
  
/*
 * Class:     StreamReceiver
 * Method:    NextOnePicLen
 * Signature: (Ljava/lang/Object;II)V
 */
JNIEXPORT jint JNICALL Java_com_example_hevcdeocderlibrary_StreamReceiver_NextOnePicLen
  (JNIEnv *, jclass);

/*
 * Class:     StreamReceiver
 * Method:    readOnePic
 * Signature: (Ljava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_com_example_hevcdeocderlibrary_StreamReceiver_readOnePic
  (JNIEnv *, jclass, jobject);
  
/*
 * Class:     StreamReceiver
 * Method:    deinit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_com_example_hevcdeocderlibrary_StreamReceiver_deinit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
