/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StreamReceiver */

#ifndef _Included_StreamReceiver
#define _Included_StreamReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StreamReceiver
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_StreamReceiver_init
  (JNIEnv *, jclass);

/*
 * Class:     StreamReceiver
 * Method:    NextOnePicLen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_StreamReceiver_NextOnePicLen
  (JNIEnv *, jclass);

/*
 * Class:     StreamReceiver
 * Method:    readOnePic
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_StreamReceiver_readOnePic
  (JNIEnv *, jclass, jobject);

/*
 * Class:     StreamReceiver
 * Method:    deinit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_StreamReceiver_deinit
  (JNIEnv *, jclass);

/*
 * Class:     StreamReceiver
 * Method:    write_int
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_StreamReceiver_write_1int
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     StreamReceiver
 * Method:    read_int
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StreamReceiver_read_1int
  (JNIEnv *, jclass, jstring);

/*
 * Class:     StreamReceiver
 * Method:    write_float
 * Signature: (Ljava/lang/String;F)Z
 */
JNIEXPORT jboolean JNICALL Java_StreamReceiver_write_1float
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     StreamReceiver
 * Method:    read_float
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_StreamReceiver_read_1float
  (JNIEnv *, jclass, jstring);

/*
 * Class:     StreamReceiver
 * Method:    videostart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_StreamReceiver_videostart
  (JNIEnv *, jclass);

/*
 * Class:     StreamReceiver
 * Method:    videostop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_StreamReceiver_videostop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
